# Generated by Django 4.2.5 on 2023-09-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_pbrand_data_brand_rename_pname_data_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='brand',
            new_name='pbrand',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='pname',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='price',
            new_name='pprice',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='stock',
            new_name='pstock',
        ),
    ]
